### ISSUE TITLE
Slow loading time

### ISSUE THREAD

**Issue by Games4k** [Seveningful/BayMaxAC#6] opened 2017-07-18 11:12 UTC
Plugin needs to up to 5-10 seconds to load on really powerfull machine. Specs:

`6-core (3.90Ghz)`
`1GB of ram` (I can allocate more, but I really dont see a point for doing that for one normal game server)

More bug reports soon...

**Comment by TheUser816** [comment] 2017-07-18 11:15
It’s not a bug.
Please consider: The AntiCheat is training itself on enable and this takes time.

> This step will take a little bit longer (about 10 seconds) since the network keeps training himself everytime the server starts

**Comment by Seveningful** [comment] 2017-07-18 11:41
Fixed on Alpha-041.
The task now executes on a asynchronous Thread.
This causes the Machine Learning part to not be available at the beginning. Once the console prints "Network trained and saved" it should be working  :)

**Closed by Seveningful** 2017-07-18 11:41 UTC
